In [1]:
import numpy as np

In [2]:
n=np.array([    [2,3,4,5],[22,33,44,55],[200,300,400,500]     ])

In [3]:
n.shape

(3, 4)

In [4]:
n

array([[  2,   3,   4,   5],
       [ 22,  33,  44,  55],
       [200, 300, 400, 500]])

In [5]:
n[2,1:3]

array([300, 400])

In [6]:
n[0,0:3]

array([2, 3, 4])

In [14]:
n[1:3,2:4]

array([[ 44,  55],
       [400, 500]])

In [9]:
n[1:,2:]

array([[ 44,  55],
       [400, 500]])

# ARANGE

In [17]:
np.arange(5.5,50.4)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# RESHAPE

In [22]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
np.sqrt(100)

10.0

In [25]:
n.max()

500

In [26]:
n.min()

2

In [27]:
n.argmax()

11

In [28]:
n.argmin()

0

In [29]:
n*2

array([[   4,    6,    8,   10],
       [  44,   66,   88,  110],
       [ 400,  600,  800, 1000]])

In [30]:
n+10

array([[ 12,  13,  14,  15],
       [ 32,  43,  54,  65],
       [210, 310, 410, 510]])

In [31]:
n/2

array([[  1. ,   1.5,   2. ,   2.5],
       [ 11. ,  16.5,  22. ,  27.5],
       [100. , 150. , 200. , 250. ]])

In [32]:
n

array([[  2,   3,   4,   5],
       [ 22,  33,  44,  55],
       [200, 300, 400, 500]])

# Random

In [33]:
np.random.rand(2,2)

array([[0.7711333 , 0.47919106],
       [0.47499212, 0.58006979]])

In [34]:
np.random.rand(2)

array([0.62740223, 0.00618863])

In [35]:
np.random.randn(2)

array([-2.53638585,  1.89813021])

In [36]:
np.random.randint(9,90,12)

array([24, 44, 75, 86, 17, 87, 49, 66, 53, 46, 58, 28])

In [45]:
s=np.random.randint(9,90,12).reshape(3,4)

In [46]:
s

array([[69, 40, 62, 81],
       [60, 86, 12, 68],
       [89, 37, 80, 36]])

In [40]:
s.sum()

663

In [41]:
s.sum(axis=1)

array([152, 168,  66,  87,  66, 124])

In [42]:
s.sum(axis=0)

array([377, 286])

# 3D

In [51]:
d=np.array([ [[4,3],[55,2] , [5,6]],[[65,7], [5,3],[23,2]],[[4,3],[5,21],[5,78]] ])

In [53]:
d.shape

(3, 3, 2)

In [54]:
(4,3,4)

(4, 3, 4)

In [55]:
# Nan - not a number


In [56]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [57]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [ ]:
x.dtype

dtype('float64')