In [6]:
import numpy as np

In [11]:
a= np.array([])
b= np.array([1,2,3,4,5])
c= np.array([[1,22,33],[2,3,4]])

In [3]:
a

array([], dtype=float64)

In [10]:
a.ndim

1

In [11]:
a.size

0

In [4]:
b

array([1, 2, 3, 4, 5])

In [6]:
type(b)

numpy.ndarray

In [9]:
b.ndim

1

In [12]:
b.size

5

In [12]:
c

array([[ 1, 22, 33],
       [ 2,  3,  4]])

In [7]:
type(c)

numpy.ndarray

In [8]:
c.ndim

2

In [13]:
c.size

6

In [13]:
c.shape

(2, 3)

In [8]:
n=np.array([    [2,3,4,5],[22,33,44,55],[200,300,400,500]     ])

In [14]:
n.shape

(3, 4)

In [15]:
n[2,2]

400

In [16]:
n

array([[  2,   3,   4,   5],
       [ 22,  33,  44,  55],
       [200, 300, 400, 500]])